server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  profiles:
    active: dev

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html